[package]
name = "rpn_converter"
version = "1.0.0"
authors = ["flevesqu <flevesqu@student.42.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
